export const websiteShowcaseCategories = [
  {
    id: "landing-pages",
    label: "Landing pages",
    description: "Focused launch, campaign, and service pages built around a clear action.",
  },
  {
    id: "business-corporate",
    label: "Business and corporate",
    description: "Professional websites for consultants, studios, teams, and service companies.",
  },
  {
    id: "ecommerce",
    label: "E-commerce stores",
    description: "Product-led storefronts with strong merchandising and checkout-ready structure.",
  },
  {
    id: "blogs-news",
    label: "Blogs and news",
    description: "Editorial layouts for publishing, personal brands, and content-heavy websites.",
  },
  {
    id: "portfolio",
    label: "Personal portfolios",
    description: "Personal websites, CV pages, and creative portfolios with strong visual identity.",
  },
  {
    id: "web-apps",
    label: "Web apps",
    description: "Dashboard and product interfaces for tools, SaaS ideas, and internal systems.",
  },
  {
    id: "3d-experiences",
    label: "3D experiences",
    description: "Interactive, motion-led pages with immersive 3D and animation direction.",
  },
] as const;

export type WebsiteShowcaseCategoryId = (typeof websiteShowcaseCategories)[number]["id"];

export type WebsiteShowcaseItem = {
  slug: string;
  name: string;
  category: WebsiteShowcaseCategoryId;
  image: string;
  description: string;
  tags: string[];
  featured?: boolean;
  liveUrl?: string;
};

export const websiteShowcaseItems: WebsiteShowcaseItem[] = [
  {
    slug: "wander-lite",
    name: "Wander Lite",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/Wander_lite.jpg",
    description: "Travel landing page with destination storytelling and booking prompts.",
    tags: ["Travel", "Lead capture", "Campaign"],
    featured: true,
  },
  {
    slug: "rs-auto",
    name: "RS Auto",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/Rs_Auto.jpg",
    description: "Automotive service landing page with a premium dark visual system.",
    tags: ["Automotive", "Service", "Local business"],
  },
  {
    slug: "pulseframe",
    name: "PulseFrame",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/PulseFrame.jpg",
    description: "Product launch page for a digital tool with concise conversion sections.",
    tags: ["SaaS", "Launch", "Product"],
  },
  {
    slug: "pr-wardrobe",
    name: "PR Wardrobe",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/PR_Wardrobe.jpg",
    description: "Fashion landing page with editorial imagery and shop-ready composition.",
    tags: ["Fashion", "Retail", "Brand"],
    featured: true,
  },
  {
    slug: "pains-et-moulins",
    name: "Pains et Moulins",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/Pains_et_Moulins.jpg",
    description: "Bakery landing page focused on craft, menu previews, and visit intent.",
    tags: ["Bakery", "Restaurant", "Local"],
  },
  {
    slug: "opsflow",
    name: "OpsFlow",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/OpsFlow.jpg",
    description: "Operations software landing page with workflow-led messaging.",
    tags: ["Operations", "B2B", "SaaS"],
  },
  {
    slug: "mood-mark",
    name: "Mood Mark",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/mood_mark.jpg",
    description: "Creative brand page with compact sections and strong art direction.",
    tags: ["Creative", "Brand", "Studio"],
  },
  {
    slug: "ignition",
    name: "Ignition",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/IGNITION.jpg",
    description: "Startup landing page for a launch offer or high-energy campaign.",
    tags: ["Startup", "Campaign", "Launch"],
  },
  {
    slug: "glow-pure",
    name: "Glow Pure",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/Glow_Pure.jpg",
    description: "Beauty and wellness landing page with soft product-led sections.",
    tags: ["Beauty", "Wellness", "Retail"],
  },
  {
    slug: "glow-jewels",
    name: "Glow Jewels",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/Glow_Jewels.jpg",
    description: "Jewelry landing page with premium product presentation and calls to action.",
    tags: ["Jewelry", "Retail", "Luxury"],
  },
  {
    slug: "eclat-candle-co",
    name: "Eclat Candle Co",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/Eclat_Candle_Co.jpg",
    description: "Lifestyle product landing page for a candle and home fragrance brand.",
    tags: ["Lifestyle", "Product", "Retail"],
  },
  {
    slug: "bright-wave-studio",
    name: "Bright Wave Studio",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/Bright_Wave_Studio.jpg",
    description: "Agency-style landing page for a small creative or marketing studio.",
    tags: ["Agency", "Creative", "Services"],
  },
  {
    slug: "automotive-concept",
    name: "Automotive Concept",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/BMW.jpg",
    description: "High-contrast automotive concept page built for product interest.",
    tags: ["Automotive", "Concept", "Premium"],
  },
  {
    slug: "aura-atelier",
    name: "Aura Atelier",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/Aura_Atelier.jpg",
    description: "Elegant studio landing page for a boutique creative or beauty brand.",
    tags: ["Studio", "Beauty", "Premium"],
  },
  {
    slug: "atelier",
    name: "Atelier",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/Atelier.jpg",
    description: "Visual-first landing page for a design, fashion, or creative studio.",
    tags: ["Design", "Fashion", "Studio"],
  },
  {
    slug: "adopt",
    name: "Adopt",
    category: "landing-pages",
    image: "/images/website-showcase/landing_page/Adopt.jpg",
    description: "Cause-led landing page with clear information blocks and action paths.",
    tags: ["Nonprofit", "Community", "Campaign"],
  },
  {
    slug: "modern-growth-studio",
    name: "Modern Growth Studio",
    category: "business-corporate",
    image: "/images/website-showcase/business_corporate/Modern_Growth_Studio.jpg",
    description: "Consulting website with structured service messaging and proof sections.",
    tags: ["Consulting", "B2B", "Services"],
    featured: true,
  },
  {
    slug: "helix-systems",
    name: "Helix Systems",
    category: "business-corporate",
    image: "/images/website-showcase/business_corporate/Helix_Systems.jpg",
    description: "Technology company website with a clean corporate layout.",
    tags: ["Technology", "Corporate", "B2B"],
  },
  {
    slug: "forge",
    name: "Forge",
    category: "business-corporate",
    image: "/images/website-showcase/business_corporate/FORGE.jpg",
    description: "Industrial brand website with bold sections and direct messaging.",
    tags: ["Industrial", "Manufacturing", "Brand"],
  },
  {
    slug: "enterprise-corporate",
    name: "Enterprise Corporate",
    category: "business-corporate",
    image: "/images/website-showcase/business_corporate/Enterprise_Corporate.jpg",
    description: "Multi-section corporate site for service teams and larger businesses.",
    tags: ["Enterprise", "Corporate", "Services"],
  },
  {
    slug: "boutique",
    name: "Boutique",
    category: "business-corporate",
    image: "/images/website-showcase/business_corporate/Boutique.jpg",
    description: "Boutique service website with polished presentation and offer blocks.",
    tags: ["Boutique", "Service", "Local"],
  },
  {
    slug: "axiom",
    name: "Axiom",
    category: "business-corporate",
    image: "/images/website-showcase/business_corporate/Axiom.jpg",
    description: "Minimal business website with strong typography and simple navigation.",
    tags: ["Business", "Minimal", "Professional"],
  },
  {
    slug: "neoncart",
    name: "NeonCart",
    category: "ecommerce",
    image: "/images/website-showcase/e-commerce_store/NEONCART.jpg",
    description: "High-energy storefront concept with strong category and product focus.",
    tags: ["Storefront", "Retail", "Product"],
  },
  {
    slug: "fieldgoods",
    name: "FieldGoods",
    category: "ecommerce",
    image: "/images/website-showcase/e-commerce_store/FieldGoods.jpg",
    description: "Natural goods store with product cards, brand story, and collection sections.",
    tags: ["Food", "Retail", "Catalog"],
    featured: true,
  },
  {
    slug: "arcvault",
    name: "ArcVault",
    category: "ecommerce",
    image: "/images/website-showcase/e-commerce_store/ARCVAULT.jpg",
    description: "Premium commerce page for curated products and limited collections.",
    tags: ["Luxury", "Catalog", "Retail"],
  },
  {
    slug: "storywave",
    name: "StoryWave",
    category: "blogs-news",
    image: "/images/website-showcase/blogs_news/StoryWave.jpg",
    description: "Publishing layout with featured articles and clear reading paths.",
    tags: ["Blog", "Publishing", "Content"],
  },
  {
    slug: "pulsefeed",
    name: "PulseFeed",
    category: "blogs-news",
    image: "/images/website-showcase/blogs_news/PulseFeed.jpg",
    description: "News-style homepage with dense but scannable content modules.",
    tags: ["News", "Media", "Editorial"],
  },
  {
    slug: "personal-brand",
    name: "Personal Brand",
    category: "blogs-news",
    image: "/images/website-showcase/blogs_news/personal_brand.jpg",
    description: "Creator and expert site with articles, positioning, and conversion sections.",
    tags: ["Creator", "Blog", "Personal"],
  },
  {
    slug: "editorial",
    name: "Editorial",
    category: "blogs-news",
    image: "/images/website-showcase/blogs_news/Editorial.jpg",
    description: "Magazine-style content website with strong visual hierarchy.",
    tags: ["Magazine", "Editorial", "Content"],
  },
  {
    slug: "columnix",
    name: "Columnix",
    category: "blogs-news",
    image: "/images/website-showcase/blogs_news/Columnix.jpg",
    description: "Column-based publishing design for long-form writing and updates.",
    tags: ["Writing", "Publishing", "Blog"],
  },
  {
    slug: "pulse-folio",
    name: "PULSE.FOLIO",
    category: "portfolio",
    image: "/images/website-showcase/personal_portfolio/PULSE.FOLIO.jpg",
    description: "Creative portfolio with bold motion direction and work highlights.",
    tags: ["Portfolio", "Creative", "Personal"],
  },
  {
    slug: "human-cv",
    name: "Human CV",
    category: "portfolio",
    image: "/images/website-showcase/personal_portfolio/human_cv.jpg",
    description: "CV and profile website for a professional personal presence.",
    tags: ["CV", "Personal", "Profile"],
  },
  {
    slug: "atelie-one",
    name: "ATELIE.ONE",
    category: "portfolio",
    image: "/images/website-showcase/personal_portfolio/ATELIE_.ONE.jpg",
    description: "Designer portfolio with minimal sections and high-impact visuals.",
    tags: ["Designer", "Portfolio", "Studio"],
  },
  {
    slug: "workbench-os",
    name: "Workbench OS",
    category: "web-apps",
    image: "/images/website-showcase/web_apps/Workbench_OS.jpg",
    description: "Operational dashboard concept for teams that need focused workflows.",
    tags: ["Dashboard", "Operations", "SaaS"],
    featured: true,
  },
  {
    slug: "neon-atlas",
    name: "Neon Atlas",
    category: "web-apps",
    image: "/images/website-showcase/web_apps/neon_atlas.jpg",
    description: "Map and analytics interface for data-led web products.",
    tags: ["Analytics", "Maps", "Product"],
  },
  {
    slug: "axiom-control",
    name: "AxiomControl",
    category: "web-apps",
    image: "/images/website-showcase/web_apps/AxiomControl.jpg",
    description: "Control panel concept with compact metrics and admin workflows.",
    tags: ["Admin", "Dashboard", "Control"],
  },
  {
    slug: "orbit",
    name: "Orbit",
    category: "3d-experiences",
    image: "/images/website-showcase/3D_animations/Orbit.jpg",
    description: "Immersive orbital 3D experience for a standout digital launch.",
    tags: ["3D", "Interactive", "Launch"],
  },
  {
    slug: "noir",
    name: "Noir",
    category: "3d-experiences",
    image: "/images/website-showcase/3D_animations/noir.jpg",
    description: "Dark cinematic 3D direction for premium brand storytelling.",
    tags: ["3D", "Cinematic", "Premium"],
  },
  {
    slug: "flux",
    name: "Flux",
    category: "3d-experiences",
    image: "/images/website-showcase/3D_animations/flux.jpg",
    description: "Motion-led 3D page concept for experimental product storytelling.",
    tags: ["3D", "Motion", "Product"],
  },
  {
    slug: "axis",
    name: "Axis",
    category: "3d-experiences",
    image: "/images/website-showcase/3D_animations/axis.jpg",
    description: "Interactive 3D visual system for technical or design-led brands.",
    tags: ["3D", "Technical", "Interactive"],
  },
];

export function getWebsiteShowcaseItemsByCategory(category: WebsiteShowcaseCategoryId) {
  return websiteShowcaseItems.filter((item) => item.category === category);
}

export function getFeaturedWebsiteShowcaseItems() {
  return websiteShowcaseItems.filter((item) => item.featured);
}
